apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chmor-prod

resources:
  - ../../base 

configMapGenerator:
  - name: env-common
    literals:
      - BACKEND_PORT=3000
      - PG_HOST=postgres
      - POSTGRES_DB=products
      - REDIS_URL=redis://redis:6379
      - CLIENT_ID=client-id
      - CLIENT_SECRET=secret
      - REDIRECT_URI=http://localhost/callback
      - SLUG=my-app
      - AUTH_URL=http://authentik:9000 
  - name: pokemons
    files:
      - pokemon.json 

secretGenerator:
  - name: pg-user
    literals:
      - PG_USER=postgres 
  - name: pg-password 
    literals:
      - PG_PASSWORD=postgres 
  - name: auth-pg-user
    literals:
      - AUTH_PG_USER=postgres 
  - name: auth-pg-password
    literals:
      - AUTH_PG_PASSWORD=postgres 
  - name: auth-secret-key
    literals:
      - AUTHENTIK_SECRET_KEY=secret 