apiVersion: v1
data:
  app.config.json: |-
    {
      "instanceName": "backend-instance",
      "timeout": 30000,
      "maxRequests": 1000,
      "logLevel": "info",
      "cacheTTL": 10
    }
kind: ConfigMap
metadata:
  labels:
    app-config: app-config
  name: app-config
